export const CONFIG = {
  BASEURL: "http://localhost:3000",
  assets: {
    airplane: "./assets/images/airplanes/Tier 1/1.png",
    bullet: "./assets/images/bullets/lvl1.png",
    bomb: "./assets/images/bullets/bomb1/lvl1.png",
    sound: "./assets/sounds/bullets/bullet1.wav",
    clouds: [
      "./assets/images/clouds/cloud1.png",
      "./assets/images/clouds/cloud2.png",
      "./assets/images/clouds/cloud3.png",
    ],
    wingmen: {
      left: "./assets/images/sideAirs/2.png",
      right: "./assets/images/sideAirs/2.png",
    },
  },
  airplane: {
    width: 100,
    height: 100,
    startX: window.innerWidth / 2 - 50,
    startY: window.innerHeight - 150,
  },
  bullets: {
    angles: [0],
    size: 25,
    speed: 5,
    interval: 900,
  },
  clouds: {
    count: 80,
    minSize: 500,
    maxSize: 900,
    minSpeed: 0.5,
    maxSpeed: 2.5,
  },
  roads: {
    images: [
      "./assets/images/roads/road1.png",
      "./assets/images/roads/road2.png",
    ],
    speed: 2,
    transitionDuration: 2000,
    width: 3840,
    height: 2160,
  },
  wingmen: {
    images: {
      left: "./assets/images/sideAirs/1.png",
      right: "./assets/images/sideAirs/2.png",
    },
    baseXOffset: 0,
    yOffset: 25,
    width: 70,
    height: 70,
    followDelay: 100,
    movementSensitivity: 0.5,
    snapBackSpeed: 0.15,
    maxPullDistance: 70,
    movementAmplitude: 10,
    movementSpeed: 0.025,
    bulletImage: "./assets/images/bullets/bullet1/lvl1.png",
    bulletSize: 20,
    bulletSpeed: 5,
    bulletAngle: 0,
    shootProbability: 0.7,
    shootDelayMultiplier: 1.5,
    rotationAngle: 5,
    minFollowDistance: 100,
    maxFollowDistance: 220,
  },
};
