const airplanesData = [
  // Tier 1
  {
    tier: 1,
    style: 1,
    name: "Tier 1 - Model 1",
    image: "assets/images/airplanes/Tier 1/1.png",
    health: 100,
    damage: 7,
    bulletSpeed: 200,
    price: 60,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "blue",
        size: 1,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "blue",
        size: 1,
        offset: "near",
      },
    ],
  },
  {
    tier: 1,
    style: 2,
    name: "Tier 1 - Model 2",
    image: "assets/images/airplanes/Tier 1/2.png",
    health: 100,
    damage: 9,
    bulletSpeed: 200,
    price: 110,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "blue",
        size: 1,
      },
    ],
  },
  {
    tier: 1,
    style: 3,
    name: "Tier 1 - Model 3",
    image: "assets/images/airplanes/Tier 1/3.png",
    health: 100,
    damage: 12,
    bulletSpeed: 200,
    price: 240,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "blue",
        size: 2,
      },
    ],
  },
  {
    tier: 1,
    style: 4,
    name: "Tier 1 - Model 4",
    image: "assets/images/airplanes/Tier 1/4.png",
    health: 100,
    damage: 13,
    bulletSpeed: 200,
    price: 360,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "blue",
        size: 2,
      },
    ],
  },
  {
    tier: 1,
    style: 5,
    name: "Tier 1 - Model 5",
    image: "assets/images/airplanes/Tier 1/5.png",
    health: 100,
    damage: 16,
    bulletSpeed: 200,
    price: 440,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "blue",
        size: 3,
      },
    ],
  },
  {
    tier: 1,
    style: 6,
    name: "Tier 1 - Model 6",
    image: "assets/images/airplanes/Tier 1/6.png",
    health: 100,
    damage: 16,
    bulletSpeed: 200,
    price: 600,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 4,
        pattern: "angled",
        color: "blue",
        size: 3,
      },
    ],
  },
  {
    tier: 1,
    style: 7,
    name: "Tier 1 - Model 7",
    image: "assets/images/airplanes/Tier 1/7.png",
    health: 120,
    damage: 19,
    bulletSpeed: 200,
    price: 800,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "blue",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "blue",
        size: 3,
        offset: "near",
      },
    ],
  },
  {
    tier: 1,
    style: 8,
    name: "Tier 1 - Model 8",
    image: "assets/images/airplanes/Tier 1/8.png",
    health: 100,
    damage: 21,
    bulletSpeed: 200,
    price: 850,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "straight",
        color: "blue",
        size: 3,
      },
    ],
  },
  {
    tier: 1,
    style: 9,
    name: "Tier 1 - Model 9",
    image: "assets/images/airplanes/Tier 1/9.png",
    health: 100,
    damage: 23,
    bulletSpeed: 220,
    price: 1000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "blue",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "blue",
        size: 5,
        offset: "near",
      },
    ],
  },
  {
    tier: 1,
    style: 10,
    name: "Tier 1 - Model 10",
    image: "assets/images/airplanes/Tier 1/10.png",
    health: 100,
    damage: 23,
    bulletSpeed: 220,
    price: 1200,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "blue",
        size: 5,
      },
    ],
  },
  {
    tier: 1,
    style: 11,
    name: "Tier 1 - Model 11",
    image: "assets/images/airplanes/Tier 1/11.png",
    health: 80,
    damage: 25,
    bulletSpeed: 240,
    price: 1450,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 1,
    style: 12,
    name: "Tier 1 - Model 12",
    image: "assets/images/airplanes/Tier 1/12.png",
    health: 130,
    damage: 25,
    bulletSpeed: 220,
    price: 1800,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "orange",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
        offset: "tip",
      },
    ],
  },
  {
    tier: 1,
    style: 13,
    name: "Tier 1 - Model 13",
    image: "assets/images/airplanes/Tier 1/13.png",
    health: 150,
    damage: 25,
    bulletSpeed: 230,
    price: 2100,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "angled",
        color: "orange",
        size: 1,
      },
    ],
  },
  {
    tier: 1,
    style: 14,
    name: "Tier 1 - Model 14",
    image: "assets/images/airplanes/Tier 1/14.png",
    health: 130,
    damage: 25,
    bulletSpeed: 240,
    price: 2400,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 1,
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "orange",
        size: 1,
        offset: "near",
      },
    ],
  },

  // Tier 2
  {
    tier: 2,
    style: 1,
    name: "Tier 2 - Model 1",
    image: "assets/images/airplanes/Tier 2/1.png",
    health: 150,
    damage: 28,
    bulletSpeed: 240,
    price: 3000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "angled",
        color: "orange",
        size: 2,
      },
    ],
  },
  {
    tier: 2,
    style: 2,
    name: "Tier 2 - Model 2",
    image: "assets/images/airplanes/Tier 2/2.png",
    health: 150,
    damage: 28,
    bulletSpeed: 240,
    price: 3200,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "orange",
        size: 2,
      },
    ],
  },
  {
    tier: 2,
    style: 3,
    name: "Tier 2 - Model 3",
    image: "assets/images/airplanes/Tier 2/3.png",
    health: 160,
    damage: 28,
    bulletSpeed: 240,
    price: 3200,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 2,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "orange",
        size: 2,
        offset: "near",
      },
    ],
  },
  {
    tier: 2,
    style: 4,
    name: "Tier 2 - Model 4",
    image: "assets/images/airplanes/Tier 2/4.png",
    health: 100,
    damage: 28,
    bulletSpeed: 270,
    price: 3500,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "orange",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 5,
    name: "Tier 2 - Model 5",
    image: "assets/images/airplanes/Tier 2/5.png",
    health: 150,
    damage: 30,
    bulletSpeed: 240,
    price: 3760,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "orange",
        size: 3,
      },
    ],
  },
  {
    tier: 2,
    style: 6,
    name: "Tier 2 - Model 6",
    image: "assets/images/airplanes/Tier 2/6.png",
    health: 120,
    damage: 30,
    bulletSpeed: 280,
    price: 4100,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "orange",
        size: 3,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 7,
    name: "Tier 2 - Model 7",
    image: "assets/images/airplanes/Tier 2/7.png",
    health: 160,
    damage: 30,
    bulletSpeed: 250,
    price: 4500,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "orange",
        size: 3,
      },
    ],
  },
  {
    tier: 2,
    style: 8,
    name: "Tier 2 - Model 8",
    image: "assets/images/airplanes/Tier 2/8.png",
    health: 120,
    damage: 32,
    bulletSpeed: 280,
    price: 5000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 9,
    name: "Tier 2 - Model 9",
    image: "assets/images/airplanes/Tier 2/9.png",
    health: 180,
    damage: 32,
    bulletSpeed: 260,
    price: 5800,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 10,
    name: "Tier 2 - Model 10",
    image: "assets/images/airplanes/Tier 2/10.png",
    health: 140,
    damage: 33,
    bulletSpeed: 280,
    price: 6200,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "angled",
        color: "orange",
        size: 5,
      },
    ],
  },
  {
    tier: 2,
    style: 11,
    name: "Tier 2 - Model 11",
    image: "assets/images/airplanes/Tier 2/11.png",
    health: 180,
    damage: 32,
    bulletSpeed: 270,
    price: 7000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 12,
    name: "Tier 2 - Model 12",
    image: "assets/images/airplanes/Tier 2/12.png",
    health: 150,
    damage: 35,
    bulletSpeed: 300,
    price: 7300,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 13,
    name: "Tier 2 - Model 13",
    image: "assets/images/airplanes/Tier 2/13.png",
    health: 190,
    damage: 35,
    bulletSpeed: 270,
    price: 8000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "orange",
        size: 5,
      },
    ],
  },
  {
    tier: 2,
    style: 14,
    name: "Tier 2 - Model 14",
    image: "assets/images/airplanes/Tier 2/14.png",
    health: 160,
    damage: 35,
    bulletSpeed: 300,
    price: 10000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "straight",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 15,
    name: "Tier 2 - Model 15",
    image: "assets/images/airplanes/Tier 2/15.png",
    health: 170,
    damage: 37,
    bulletSpeed: 290,
    price: 12000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 1,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 1,
      },
    ],
  },
  {
    tier: 2,
    style: 16,
    name: "Tier 2 - Model 16",
    image: "assets/images/airplanes/Tier 2/16.png",
    health: 190,
    damage: 36,
    bulletSpeed: 290,
    price: 14000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 2,
        offset: "near",
      },
    ],
  },
  {
    tier: 2,
    style: 17,
    name: "Tier 2 - Model 17",
    image: "assets/images/airplanes/Tier 2/17.png",
    health: 200,
    damage: 37,
    bulletSpeed: 300,
    price: 17000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 2,
      },
    ],
  },
  {
    tier: 2,
    style: 18,
    name: "Tier 2 - Model 18",
    image: "assets/images/airplanes/Tier 2/18.png",
    health: 200,
    damage: 38,
    bulletSpeed: 290,
    price: 20000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 1,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 1,
        offset: "near",
      },
    ],
  },
  {
    tier: 2,
    style: 19,
    name: "Tier 2 - Model 19",
    image: "assets/images/airplanes/Tier 2/19.png",
    health: 200,
    damage: 38,
    bulletSpeed: 300,
    price: 23000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 2,
        offset: "near",
      },
    ],
  },
  {
    tier: 2,
    style: 20,
    name: "Tier 2 - Model 20",
    image: "assets/images/airplanes/Tier 2/20.png",
    health: 200,
    damage: 38,
    bulletSpeed: 300,
    price: 25000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "red",
        size: 2,
      },
    ],
  },

  // Tier 3
  {
    tier: 3,
    style: 1,
    name: "Tier 3 - Model 1",
    image: "assets/images/airplanes/Tier 3/1.png",
    health: 200,
    damage: 40,
    bulletSpeed: 300,
    price: 30000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "red",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 2,
    name: "Tier 3 - Model 2",
    image: "assets/images/airplanes/Tier 3/2.png",
    health: 220,
    damage: 40,
    bulletSpeed: 300,
    price: 33000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 3,
        offset: "near",
      },
    ],
  },
  {
    tier: 3,
    style: 3,
    name: "Tier 3 - Model 3",
    image: "assets/images/airplanes/Tier 3/3.png",
    health: 220,
    damage: 40,
    bulletSpeed: 300,
    price: 40000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "red",
        size: 3,
      },
    ],
  },
  {
    tier: 3,
    style: 4,
    name: "Tier 3 - Model 4",
    image: "assets/images/airplanes/Tier 3/4.png",
    health: 220,
    damage: 42,
    bulletSpeed: 300,
    price: 45000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 5,
    name: "Tier 3 - Model 5",
    image: "assets/images/airplanes/Tier 3/5.png",
    health: 230,
    damage: 42,
    bulletSpeed: 300,
    price: 48000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
        offset: "tip",
      },
    ],
  },
  {
    tier: 3,
    style: 6,
    name: "Tier 3 - Model 6",
    image: "assets/images/airplanes/Tier 3/6.png",
    health: 240,
    damage: 42,
    bulletSpeed: 300,
    price: 52000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "red",
        size: 3,
        offset: "near",
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 7,
    name: "Tier 3 - Model 7",
    image: "assets/images/airplanes/Tier 3/7.png",
    health: 240,
    damage: 42,
    bulletSpeed: 310,
    price: 57000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 3,
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "red",
        size: 3,
      },
    ],
  },
  {
    tier: 3,
    style: 8,
    name: "Tier 3 - Model 8",
    image: "assets/images/airplanes/Tier 3/8.png",
    health: 200,
    damage: 44,
    bulletSpeed: 330,
    price: 61000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "red",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 9,
    name: "Tier 3 - Model 9",
    image: "assets/images/airplanes/Tier 3/9.png",
    health: 240,
    damage: 42,
    bulletSpeed: 310,
    price: 68000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 4,
        pattern: "angled",
        color: "red",
        size: 5,
      },
    ],
  },
  {
    tier: 3,
    style: 10,
    name: "Tier 3 - Model 10",
    image: "assets/images/airplanes/Tier 3/10.png",
    health: 200,
    damage: 44,
    bulletSpeed: 330,
    price: 74000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 11,
    name: "Tier 3 - Model 11",
    image: "assets/images/airplanes/Tier 3/11.png",
    health: 200,
    damage: 44,
    bulletSpeed: 330,
    price: 80000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 12,
    name: "Tier 3 - Model 12",
    image: "assets/images/airplanes/Tier 3/12.png",
    health: 250,
    damage: 43,
    bulletSpeed: 310,
    price: 90000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 13,
    name: "Tier 3 - Model 13",
    image: "assets/images/airplanes/Tier 3/13.png",
    health: 250,
    damage: 43,
    bulletSpeed: 320,
    price: 100000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "purple",
        size: 1,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 3,
        offset: "near",
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "purple",
        size: 1,
      },
    ],
  },
  {
    tier: 3,
    style: 14,
    name: "Tier 3 - Model 14",
    image: "assets/images/airplanes/Tier 3/14.png",
    health: 220,
    damage: 46,
    bulletSpeed: 340,
    price: 120000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 3,
        offset: "near",
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 15,
    name: "Tier 3 - Model 15",
    image: "assets/images/airplanes/Tier 3/15.png",
    health: 260,
    damage: 44,
    bulletSpeed: 320,
    price: 135000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "red",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "straight",
        size: 3,
        offset: "near",
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 1,
      },
    ],
  },
  {
    tier: 3,
    style: 16,
    name: "Tier 3 - Model 16",
    image: "assets/images/airplanes/Tier 3/16.png",
    health: 260,
    damage: 44,
    bulletSpeed: 330,
    price: 140000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "angled",
        color: "purple",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 17,
    name: "Tier 3 - Model 17",
    image: "assets/images/airplanes/Tier 3/17.png",
    health: 270,
    damage: 46,
    bulletSpeed: 330,
    price: 160000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "purple",
        size: 2,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "homing",
        size: 2,
      },
    ],
  },
  {
    tier: 3,
    style: 18,
    name: "Tier 3 - Model 18",
    image: "assets/images/airplanes/Tier 3/18.png",
    // اطلاعات زیر اضافه شده است
    health: 280,
    damage: 47,
    bulletSpeed: 330,
    price: 180000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "purple",
        size: 3,
      },
    ],
  },
  {
    tier: 3,
    style: 19,
    name: "Tier 3 - Model 19",
    image: "assets/images/airplanes/Tier 3/19.png",
    // اطلاعات زیر اضافه شده است
    health: 300,
    damage: 48,
    bulletSpeed: 330,
    price: 190000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
    ],
  },

  // Tier 4
  {
    tier: 4,
    style: 1,
    name: "Tier 4 - Model 1",
    image: "assets/images/airplanes/Tier 4/1.png",
    health: 290,
    damage: 50,
    bulletSpeed: 330,
    price: 200000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 5,
        pattern: "angled",
        color: "purple",
        size: 3,
      },
    ],
  },
  {
    tier: 4,
    style: 2,
    name: "Tier 4 - Model 2",
    image: "assets/images/airplanes/Tier 4/2.png",
    health: 290,
    damage: 50,
    bulletSpeed: 330,
    price: 220000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 1,
        pattern: "straight",
        color: "purple",
        size: 3,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 3,
        offset: "near",
      },
    ],
  },
  {
    tier: 4,
    style: 3,
    name: "Tier 4 - Model 3",
    image: "assets/images/airplanes/Tier 4/3.png",
    health: 320,
    damage: 55,
    bulletSpeed: 350,
    price: 250000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 3,
      },
    ],
  },
  {
    tier: 4,
    style: 4,
    name: "Tier 4 - Model 4",
    image: "assets/images/airplanes/Tier 4/4.png",
    health: 300,
    damage: 50,
    bulletSpeed: 330,
    price: 270000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
    ],
  },
  {
    tier: 4,
    style: 5,
    name: "Tier 4 - Model 5",
    image: "assets/images/airplanes/Tier 4/5.png",
    health: 300,
    damage: 51,
    bulletSpeed: 330,
    price: 300000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 3,
      },
      {
        type: "missile",
        from: "wings",
        count: 4,
        missileType: "homing",
        size: 3,
      },
    ],
  },
  {
    tier: 4,
    style: 6,
    name: "Tier 4 - Model 6",
    image: "assets/images/airplanes/Tier 4/6.png",
    health: 320,
    damage: 52,
    bulletSpeed: 330,
    price: 350000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 3,
        offset: "near",
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 3,
      },
    ],
  },
  {
    tier: 4,
    style: 7,
    name: "Tier 4 - Model 7",
    image: "assets/images/airplanes/Tier 4/7.png",
    health: 320,
    damage: 52,
    bulletSpeed: 330,
    price: 390000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 4,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 3,
        offset: "near",
      },
      {
        type: "bullet",
        from: "wings",
        count: 2,
        pattern: "straight",
        color: "purple",
        size: 2,
      },
    ],
  },
  {
    tier: 4,
    style: 8,
    name: "Tier 4 - Model 8",
    image: "assets/images/airplanes/Tier 4/8.png",
    health: 330,
    damage: 53,
    bulletSpeed: 330,
    price: 450000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 2,
        missileType: "homing",
        size: 5,
        offset: "near",
      },
      {
        type: "bullet",
        from: "wings",
        count: 4,
        pattern: "straight",
        color: "purple",
        size: 2,
      },
    ],
  },
  {
    tier: 4,
    style: 9,
    name: "Tier 4 - Model 9",
    image: "assets/images/airplanes/Tier 4/9.png",
    health: 350,
    damage: 56,
    bulletSpeed: 340,
    price: 500000,
    projectiles: [
      {
        type: "bullet",
        from: "nose",
        count: 3,
        pattern: "straight",
        color: "purple",
        size: 5,
      },
      {
        type: "missile",
        from: "wings",
        count: 6,
        missileType: "homing",
        size: 4,
      },
    ],
  },
];

// دیتای معجون‌ها و گلوله‌های پیش‌فرض (می‌توانید بعداً تکمیل کنید)
const potionsData = [
  {
    name: "معجون سرعت",
    description: "سرعت حرکت هواپیما را افزایش می‌دهد",
    effect: "افزایش ۲۰٪ سرعت به مدت ۳۰ ثانیه",
    price: 50,
    imagePath: "assets/images/potions/speed.png",
    cooldown: 30,
  },
  {
    name: "معجون قدرت",
    description: "قدرت حمله را افزایش می‌دهد",
    effect: "افزایش ۲۵٪ damage به مدت ۲۰ ثانیه",
    price: 70,
    imagePath: "assets/images/potions/power.png",
    cooldown: 20,
  },
  {
    name: "معجون محافظ",
    description: "یک سپر دفاعی ایجاد می‌کند",
    effect: "ایمنی کامل در برابر damage به مدت ۱۰ ثانیه",
    price: 100,
    imagePath: "assets/images/potions/shield.png",
    cooldown: 10,
  },
  {
    name: "معجون درمان",
    description: "سلامتی هواپیما را بازیابی می‌کند",
    effect: "بازیابی ۵۰٪ سلامت",
    price: 80,
    imagePath: "assets/images/potions/heal.png",
    cooldown: 0,
  },
];
const bulletsData = [
  { id: 1, name: "Level 1", image: "assets/images/bullets/lvl1.png" },
];

const wingmenData = [
  {
    level: 1,
    name: "همراه سطح ۱",
    image: "assets/images/sideAirs/1.png",
    damage: 2,
    upgradeCost: 500,
  },
  {
    level: 2,
    name: "همراه سطح ۲",
    image: "assets/images/sideAirs/2.png",
    damage: 3,
    upgradeCost: 1000,
  },
  {
    level: 3,
    name: "همراه سطح ۳",
    image: "assets/images/sideAirs/3.png",
    damage: 4,
    upgradeCost: 2200,
  },
  {
    level: 4,
    name: "همراه سطح ۴",
    image: "assets/images/sideAirs/4.png",
    damage: 5,
    upgradeCost: 4500,
  },
  {
    level: 5,
    name: "همراه سطح ۵",
    image: "assets/images/sideAirs/5.png",
    damage: 7,
    upgradeCost: 9000,
  },
  {
    level: 6,
    name: "همراه سطح ۶",
    image: "assets/images/sideAirs/6.png",
    damage: 8,
    upgradeCost: 18000,
  },
  {
    level: 7,
    name: "همراه سطح ۷",
    image: "assets/images/sideAirs/7.png",
    damage: 10,
    upgradeCost: 35000,
  },
  {
    level: 8,
    name: "همراه سطح ۸",
    image: "assets/images/sideAirs/8.png",
    damage: 12,
    upgradeCost: 70000,
  },
  {
    level: 9,
    name: "همراه سطح ۹",
    image: "assets/images/sideAirs/9.png",
    damage: 14,
    upgradeCost: 150000,
  },
  {
    level: 10,
    name: "همراه سطح ۱۰",
    image: "assets/images/sideAirs/10.png",
    damage: 16,
    upgradeCost: 300000,
  },
  {
    level: 11,
    name: "همراه سطح ۱۱",
    image: "assets/images/sideAirs/11.png",
    damage: 18,
    upgradeCost: 600000,
  },
  {
    level: 12,
    name: "همراه سطح ۱۲",
    image: "assets/images/sideAirs/12.png",
    damage: 20,
    upgradeCost: 0,
  }, // سطح آخر هزینه ارتقا ندارد
];

module.exports = { airplanesData, potionsData, bulletsData, wingmenData };
